services:
  pgvector:
    restart: always
    image: whatwewant/pgvector:${SERVICE_PGVECTOR_IMAGE_VERSION}
    # ports:
    #   - 0.0.0.0:${SERVICE_PGVECTOR_PORT}:5432
    environment:
      POSTGRES_USER: ${SERVICE_PGVECTOR_POSTGRES_USER}
      POSTGRES_PASSWORD: ${SERVICE_PGVECTOR_POSTGRES_PASSWORD}
      POSTGRES_DB: ${SERVICE_PGVECTOR_POSTGRES_DB}
    volumes:
      - ${SERVICE_DATA}:/var/lib/postgresql/data
      
networks:
  default:
    external: true
    name: compose-ingress
